SHOW DATABASES;
USE PORTFOLIO
SHOW TABLES;
DROP TABLE IF EXISTS LITERACY;
CREATE TABLE LITERACY
(
Num	int,
State VARCHAR(20),
Literacy FLOAT,
Male INT,
FEMALE INT,
CHNGE float
)

#Data has been inserted here using cmd prompt

SELECT * FROM LITERACY;

CREATE TABLE DEMOGRAPHICS
(
Numb int,
District VARCHAR(20),
State VARCHAR(20),
Population INT,
Growth float,
SexRatio INT,
Literacy float
)

SELECT * FROM DEMOGRAPHICS;

#Find the total number of records in each dataset
SELECT COUNT(*) FROM DEMOGRAPHICS;
SELECT COUNT(*) FROM LITERACY;

#Generate data only for Bihar & Jharkhand
Select * from DEMOGRAPHICS WHERE STATE IN ('Bihar', 'Jharkhand');

#Find Population of India
SELECT SUM(POPULATION) AS India_Population FROM DEMOGRAPHICS;

#Find average growth of India
SELECT ROUND(AVG(GROWTH)*100,4) AS AVG_India_growth FROM DEMOGRAPHICS;

#Find average growth of each state and find top 3 giving max growth rate
SELECT STATE,ROUND(AVG(GROWTH)*100,4) AS AVG_growth_PERC FROM DEMOGRAPHICS GROUP BY STATE ORDER BY AVG_GROWTH_PERC DESC;
SELECT STATE,ROUND(AVG(GROWTH)*100,4) AS AVG_growth_PERC FROM DEMOGRAPHICS GROUP BY STATE ORDER BY AVG_GROWTH_PERC DESC LIMIT 3;

#Find Average Sex Ratio
SELECT state,ROUND(AVG(SEXRatio),0) AS AVG_SEX_RATIO FROM DEMOGRAPHICS group by state ORDER BY AVG_sEX_RATIO DESC;

#Find Average Literacy rate OF STATES WHERE LITERACY RATE >90
SELECT STATE,TRUNCATE(AVG(LITERACY),0) AS AVG_LITERACY_RATE FROM LITERACY GROUP BY STATE HAVING AVG(LITERACY)>90 ORDER BY AVG_LITERACY_RATE DESC;

#Find bottom 3 states showing lowest sex ratio
SELECT state,ROUND(AVG(SEXRatio),0) AS AVG_SEX_RATIO FROM DEMOGRAPHICS group by state ORDER BY AVG_sEX_RATIO asc limit 3;

#Find top and bottom 3 states in literacy rates
SELECT STATE,TRUNCATE(AVG(LITERACY),0) AS AVG_LITERACY_RATE FROM LITERACY GROUP BY STATE ORDER BY AVG_LITERACY_RATE DESC;

#Find the name of states starting with letter A
SELECT State FROM LITERACY WHERE LOWER(STATE) LIKE "a%"

#Find the name of states starting with letter A or letter B
SELECT State FROM LITERACY WHERE STATE REGEXP '^[ab]'
SELECT State FROM LITERACY WHERE LOWER(STATE) LIKE "a%" OR LOWER(STATE) LIKE "b%"

#Find the name of states starting with letter A and ending in letter m
SELECT State FROM LITERACY WHERE LOWER(STATE) LIKE "a%" AND LOWER(STATE) LIKE "%m"

#Find the TOTAL number of MALES & Females in EACH STATE
SELECT state, ROUND(Population/(1+Sexratio/1000),0) as Total_males,ROUND(POPULATION*SEXRatio/(1000+Sexratio),0) as total_females FROM DEMOGRAPHICS GROUP BY state order by STATE ASC;

#Find the total literacy rate
#First step is to get populations on a state level..we make a temporary table State_pop

DROP TABLE IF EXISTS STATE_POP
CREATE TABLE STATE_POP
(
STATE VARCHAR(25),
POPULATION INT
)

INSERT INTO STATE_POP
SELECT STATE,POPULATION FROM DEMOGRAPHICS GROUP BY STATE ORDER BY STATE

SELECT * FROM STATE_POP
SELECT * FROM LITERACY 

#Find literate and illeterate people
SELECT A.STATE,B.POPULATION,A.LITERACY,ROUND(A.LITERACY*B.POPULATION/100,0) AS Literate_people, ROUND((100-A.LITERACY)*B.POPULATION/100,0) AS Illiterate_people FROM LITERACY AS A INNER JOIN STATE_POP AS B ON A.STATE=B.STATE
SELECT A.STATE,ROUND(A.LITERACY*B.POPULATION/100,0) AS Literate_people, ROUND((100-A.LITERACY)*B.POPULATION/100,0) AS Illiterate_people FROM LITERACY AS A INNER JOIN STATE_POP AS B ON A.STATE=B.STATE GROUP BY A.STATE

DROP TABLE IF EXISTS LITERACY_COUNT
CREATE TABLE LITERACY_COUNT
(
STATE VARCHAR(25),
LITERATE_PEOPLE INT,
POPULATION INT
)

INSERT INTO LITERACY_COUNT 
(
SELECT A.STATE,ROUND(A.LITERACY*B.POPULATION/100,0),B.POPULATION FROM LITERACY AS A INNER JOIN STATE_POP AS B ON A.STATE=B.STATE
)

SELECT * FROM LITERACY_COUNT
SELECT ROUND(100*SUM(LITERATE_PEOPLE)/SUM(POPULATION),2) AS OVERALL_LITERACY_PERCENTAGE FROM LITERACY_COUNT 


#Population of previous census
SELECT DISTRICT,ROUND(population/(1+growth),0) as prev_pop,ROUND(growth*100,2) AS GROWTH_PERCENTAGE,population AS CURRENT_POP FROM DEMOGRAPHICS
SELECT SUM(ROUND(population/(1+growth),0)) as prev_pop, SUM(population) AS CURRENT_POP FROM DEMOGRAPHICS


#Top 3 districts in each state having highest literacy ratio
SELECT A.* FROM (SELECT DISTRICT, STATE, LITERACY, RANK() OVER (PARTITION BY STATE ORDER BY LITERACY DESC) AS RNK FROM DEMOGRAPHICS) A WHERE RNK IN (1,2,3) ORDER BY STATE

#Bottom 3 districts in each state having highest literacy ratio
SELECT * FROM (SELECT DISTRICT, STATE, LITERACY, RANK() OVER (PARTITION BY STATE ORDER BY LITERACY ASC) AS RNK FROM DEMOGRAPHICS) A WHERE A.RNK IN (1,2,3) ORDER BY STATE